# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default   # or whatever your self-hosted agent pool is named

steps:
- script: echo "Hello from Azure Pipelines"
  displayName: 'Run echo script'
